---
- name: download kubeadm MD5
  get_url:
    url: "{{ kubernetes_binary_url }}/kubeadm.MD5"
    dest: /tmp

- name: check md5
  shell: "[[ \"$(md5sum /usr/bin/kubeadm|awk '{print $1}')\" == \"$(cat /tmp/kubeadm.MD5)\" ]]"
  register: md5_result
  ignore_errors: true

- debug:
    msg: "{{ md5_result }}"

- name: fetch kubeadm binary to PATH(/usr/bin)
  get_url:
    url: "{{ kubernetes_binary_url }}/kubeadm"
    dest: /usr/bin
    owner: root
    group: root
    mode: 0755
  when: md5_result.rc != 0
