---
- name: sync ssl certs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'kubeconfig', dest: '/etc/kubernetes/kubeconfig' }
    - { src: 'pki/ca.crt', dest: '/etc/kubernetes/pki/ca.crt' }
