---
- name: remove apiserver, controller-manager, scheduler
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/kubernetes/manifests/kube-apiserver.yaml
    - /etc/kubernetes/manifests/kube-controller-manager.yaml
    - /etc/kubernetes/manifests/kube-scheduler.yaml
