---
- name: sync ssl certs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'bootstrap.kubeconfig', dest: '/etc/kubernetes/bootstrap.kubeconfig' }
    - { src: 'kubelet.kubeconfig', dest: '/etc/kubernetes/kubelet.kubeconfig' }
    - { src: 'kubeconfig', dest: '/etc/kubernetes/kubeconfig' }
    - { src: 'pki/k8s-root-ca.pem', dest: '/etc/kubernetes/pki/k8s-root-ca.pem' }
