apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: {{ kube_hyperkube_image }}
    command:
    - /bin/sh
    - -c
    - /usr/local/bin/kube-proxy
      --master={{ kubernetes_apiserver }}
      --proxy-mode=iptables
      --cluster-cidr={{ calico_ipv4pool_cidr }}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: srvkube
      readOnly: true
    - mountPath: /var/log
      name: varlog
      readOnly: false
    - mountPath: /run/xtables.lock
      name: xtables-lock
      readOnly: false
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: srvkube
  - name: varlog
    hostPath:
      path: /var/log
  - name: xtables-lock
    hostPath:
      path: /run/xtables.lock
      type: FileOrCreate
  - name: lib-modules
    hostPath:
      path: /lib/modules
