---
- name: sync ssl certs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'bootstrap.kubeconfig', dest: '/etc/kubernetes/bootstrap.kubeconfig' }
    - { src: 'kubelet.kubeconfig', dest: '/etc/kubernetes/kubelet.kubeconfig' }
    - { src: 'kubeconfig', dest: '/etc/kubernetes/kubeconfig' }
    - { src: 'pki/k8s-root-ca.pem', dest: '/etc/kubernetes/pki/k8s-root-ca.pem' }
    - { src: 'pki/k8s-root-ca-key.pem', dest: '/etc/kubernetes/pki/k8s-root-ca-key.pem' }
    - { src: 'pki/kubernetes.pem', dest: '/etc/kubernetes/pki/kubernetes.pem' }
    - { src: 'pki/kubernetes-key.pem', dest: '/etc/kubernetes/pki/kubernetes-key.pem' }
    - { src: 'pki/kubelet.pem', dest: '/etc/kubernetes/pki/kubelet.pem' }
    - { src: 'pki/kubelet-key.pem', dest: '/etc/kubernetes/pki/kubelet-key.pem' }
    - { src: 'pki/known_tokens.csv', dest: '/etc/kubernetes/pki/known_tokens.csv' }
