---
- import_tasks: kubeconfig.yml
  tags: kubeconfig
- import_tasks: kube-apiserver.yml
  tags: kube-apiserver
- import_tasks: kube-controller-manager.yml
  tags: kube-controller-manager
- import_tasks: kube-scheduler.yml
  tags: kube-scheduler
- import_tasks: kube-proxy.yml
  tags: kube-proxy
