---
- name: touch /var/log/kube-apiserver.log
  file:
    path: /var/log/kube-apiserver.log
    state: touch
    mode: 0644

- name: create kube-apiserver
  template: 
    src: kube-apiserver.yaml
    dest: /etc/kubernetes/manifests/kube-apiserver.yaml
    owner: root
    group: root
    mode: 0644
