---
- name: touch /var/log/kube-apiserver.log
  command: touch /var/log/kube-apiserver.log

- name: create kube-apiserver
  template: 
    src: kube-apiserver.yaml
    dest: /etc/kubernetes/manifests/kube-apiserver.yaml
    owner: root
    group: root
    mode: 0644
