---
- name: touch /var/log/kube-scheduler.log
  file:
    path: /var/log/kube-scheduler.log
    state: touch
    mode: 0644

- name: create kube-scheduler
  template: 
    src: kube-scheduler.yaml
    dest: /etc/kubernetes/manifests/kube-scheduler.yaml
    owner: root
    group: root
    mode: 0644
