---
- name: touch /var/log/kube-controller-manager.log
  file:
    path: /var/log/kube-controller-manager.log
    state: touch
    mode: 0644

- name: create kube-controller-manager
  template: 
    src: kube-controller-manager.yaml
    dest: /etc/kubernetes/manifests/kube-controller-manager.yaml
    owner: root
    group: root
    mode: 0644
