---
- name: sync ssl certs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'kubeconfig', dest: '/etc/kubernetes/kubeconfig' }
    - { src: 'pki/ca.crt', dest: '/etc/kubernetes/pki/ca.crt' }
    - { src: 'pki/server.crt', dest: '/etc/kubernetes/pki/server.crt' }
    - { src: 'pki/server.key', dest: '/etc/kubernetes/pki/server.key' }
    - { src: 'pki/basic_auth.csv', dest: '/etc/kubernetes/pki/basic_auth.csv' }
    - { src: 'pki/known_tokens.csv', dest: '/etc/kubernetes/pki/known_tokens.csv' }
