---
- name: stop the docker service
  service: 
    name: docker 
    state: stopped 
    enabled: no
  ignore_errors: true

- name: uninstall docker
  yum: 
    name: "{{ item }}"
    state: absent
    update_cache: yes
  with_items:
    - docker
    - docker-common
    - docker-client

- name: remove docker yum repo
  yum_repository:
    name: docker
    state: absent

- name: remove docker directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/docker
    - /var/lib/docker
    - /var/run/docker
    - /etc/sysconfig/docker
    - /etc/sysconfig/docker-network
    - /etc/sysconfig/docker-storage
    - /etc/sysconfig/docker-storage-setup
    - /etc/yum.repos.d/docker.repo
